### ISSUE TITLE
Please add a LICENSE file to the project.

### ISSUE THREAD

**Issue by kgambrel** [LumaPictures/usd-qt-components#3]
We're very interested in using this project, even with the temporary nature of it, but it must be approved for use prior to downloading.  Approving for use involves a few things, including making sure the project actually has an open source license associated with it, preferably in a LICENSE file in the root directory of the project.  
We're good with any license from the opensource.org list of licenses.

**Comment by chadrik** [comment]
Hi Kevin, I was *just* cleaning this up in preparation for siggraph.  Now that Pixar is on board with helping us to incubate this, I decided to move this to the slightly more official-sounding https://github.com/LumaPictures/usd-qt.  Nothing there yet, but stay tuned.  For simplicity, we'll be using the same Modified Apache 2.0 License as USD.

**Comment by kgambrel** [comment]
Thanks. I actually work for Disney animation.   We're looking forward to your official releases.

**Comment by chadrik** [comment]
done:  https://github.com/LumaPictures/usd-qt/commit/f70c3d0428674720d05d4e997cfd90e0010e206e
